<?php

/**
 * @file
 * All the stuff.
 */

/**
 * Implements hook_islandora_simple_map_get_coordinates().
 */
function example_degrees_coords_islandora_simple_map_get_coordinates(AbstractObject $object) {
  module_load_include('inc', 'islandora_simple_map', 'includes/utilities');
  $found_coords = [];
  $node_results = islandora_simple_map_get_mods_results($object);
  foreach ($node_results as $value) {
    if (strlen(trim(variable_get('islandora_simple_map_coordinate_delimiter', ';'))) > 0) {
      $temp_array = explode(trim(variable_get('islandora_simple_map_coordinate_delimiter', ';')), $value);
      foreach ($temp_array as $item) {
        if (preg_match_all("/(\d+)°?(\s+[\d\.]+'?)?(\s+[\d\.]+\"?)?\s*([NSEW])\s*,?/u", trim($item), $matches, PREG_SET_ORDER, 0)) {
          foreach ($matches as $match) {
            if ($match[count($match) - 1] == 'N' || $match[count($match) - 1] == 'S') {
              $lat = example_degrees_coords_convert_to_decimal($match);
            }
            else {
              $long = example_degrees_coords_convert_to_decimal($match);
            }
          }
          if (isset($lat) && isset($long)) {
            $found_coords[] = format_string('!lat,!long',
              [
                '!lat' => $lat,
                '!long' => $long,
              ]
            );
          }
        }
      }
    }
  }
  return $found_coords;
}

/**
 * Does the actual calculation of DMS to decimal.
 *
 * @param array $coord
 *   Array of regexp match.
 *
 * @return string
 *   lat,lng decimal format.
 */
function example_degrees_coords_convert_to_decimal(array $coord) {
  $decimal = 0;
  $pos_neg = FALSE;
  $clean = function ($c) {
    return str_replace('"', '', str_replace('\'', '', trim($c)));
  };
  for ($bar = count($coord) - 1; $bar > 1; $bar -= 1) {
    if (preg_match('/^[NSEW]?$/', $coord[$bar])) {
      $pos_neg = ($coord[$bar] == 'N' || $coord[$bar] == 'E');
    }
    else {
      $num = $clean($coord[$bar]);
      if (is_numeric($num)) {
        $decimal += $num;
      }
    }
    $decimal = $decimal / 60;
  }
  $decimal += $clean($coord[1]);
  $decimal *= ($pos_neg ? 1 : -1);
  return $decimal;
}
